# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# uv-nc_to_s-tif.py
# Created on: 2014-10-14 12:40:57.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

#执行栅格计算时出现Error:  ERROR 000539: Error running expression: rcexec()错误，在网上找到的解决方法
from arcpy import env
from arcpy.sa import *
env.workspace = "c:/users/wj/esm296-4f/labs/lab2"

# Check out any necessary licenses
arcpy.CheckOutExtension("spatial")


# Local variables:
v_nc = "C:\\Users\\wj\\esm296-4f\\labs\\lab2\\raw\\uwnd.sig995.2013.nc"
u_nc = "C:\\Users\\wj\\esm296-4f\\labs\\lab2\\raw\\vwnd.sig995.2013.nc"

# Local variables:
in_countries = "C:\\Users\\wj\\esm296-4f\\labs\\lab2\\raw\\World_EEZ_v8_2014.shp"
s_0_tif = "C:\\Users\\wj\\esm296-4f\\labs\\lab2\\out\\s_000.tif"
s_120_tif = "C:\\Users\\wj\\esm296-4f\\labs\\lab2\\out\\s_120.tif"
s_150_tif = "C:\\Users\\wj\\esm296-4f\\labs\\lab2\\out\\s_150.tif"
s_180_tif = "C:\\Users\\wj\\esm296-4f\\labs\\lab2\\out\\s_180.tif"
s_210_tif = "C:\\Users\\wj\\esm296-4f\\labs\\lab2\\out\\s_210.tif"
s_240_tif = "C:\\Users\\wj\\esm296-4f\\labs\\lab2\\out\\s_240.tif"
s_270_tif = "C:\\Users\\wj\\esm296-4f\\labs\\lab2\\out\\s_270.tif"
s_30_tif = "C:\\Users\\wj\\esm296-4f\\labs\\lab2\\out\\s_030.tif"
s_300_tif = "C:\\Users\\wj\\esm296-4f\\labs\\lab2\\out\\s_300.tif"
s_330_tif = "C:\\Users\\wj\\esm296-4f\\labs\\lab2\\out\\s_330.tif"
s_360_tif = "C:\\Users\\wj\\esm296-4f\\labs\\lab2\\out\\s_360.tif"
s_60_tif = "C:\\Users\\wj\\esm296-4f\\labs\\lab2\\out\\s_060.tif"
s_90_tif = "C:\\Users\\wj\\esm296-4f\\labs\\lab2\\out\\s_090.tif"
s_avg_tif = "C:\\Users\\wj\\esm296-4f\\labs\\lab2\\out\\s_avg.tif"
out_countries = "C:\\Users\\wj\\esm296-4f\\labs\\lab2\\lab2.gdb\\countries_out"
s_countries = "C:\\Users\\wj\\esm296-4f\\labs\\lab2\\lab2.gdb\\s_countries"


# place loop

for j in range(0, 365, 30):
    u_001 = "u_%03d" %j
    v_001 = "v_%03d" %j
    s_001 = "s_%03d" %j
    s_001_tif = "c:\\users\\wj\\esm296-4f\\labs\\lab2\\out\\s_%03d.tif" % j
    print s_001_tif

    # Process: Make NetCDF Raster Layer
    arcpy.MakeNetCDFRasterLayer_md(v_nc, "uwnd", "lon", "lat", u_001, "", "time 1", "BY_INDEX")

    # Process: Make NetCDF Raster Layer (2)
    arcpy.MakeNetCDFRasterLayer_md(u_nc, "vwnd", "lon", "lat", v_001, "", "time 1", "BY_INDEX")

    # Process: Raster Calculator
    arcpy.gp.RasterCalculator_sa("SquareRoot( Square('%s') + Square('%s') )" % (u_001,v_001), s_001)

    # Process: Resample
    arcpy.Resample_management(s_001, s_001_tif, ".25 .25", "BILINEAR")


arcpy.env.overwriteOutput = True

# Process: Copy Features
arcpy.CopyFeatures_management(in_countries, out_countries, "", "0", "0", "0")

# Process: Cell Statistics
arcpy.gp.CellStatistics_sa("C:\\Users\\wj\\esm296-4f\\labs\\lab2\\out\\s_000.tif;C:\\Users\\wj\\esm296-4f\\labs\\lab2\\out\\s_120.tif;C:\\Users\\wj\\esm296-4f\\labs\\lab2\\out\\s_150.tif;C:\\Users\\wj\\esm296-4f\\labs\\lab2\\out\\s_180.tif;C:\\Users\\wj\\esm296-4f\\labs\\lab2\\out\\s_210.tif;C:\\Users\\wj\\esm296-4f\\labs\\lab2\\out\\s_240.tif;C:\\Users\\wj\\esm296-4f\\labs\\lab2\\out\\s_270.tif;C:\\Users\\wj\\esm296-4f\\labs\\lab2\\out\\s_030.tif;C:\\Users\\wj\\esm296-4f\\labs\\lab2\\out\\s_300.tif;C:\\Users\\wj\\esm296-4f\\labs\\lab2\\out\\s_330.tif;C:\\Users\\wj\\esm296-4f\\labs\\lab2\\out\\s_360.tif;C:\\Users\\wj\\esm296-4f\\labs\\lab2\\out\\s_060.tif;C:\\Users\\wj\\esm296-4f\\labs\\lab2\\out\\s_090.tif", s_avg_tif, "MEAN", "DATA")

# Process: Zonal Statistics as Table
arcpy.gp.ZonalStatisticsAsTable_sa(out_countries, "Country", s_avg_tif, s_countries, "DATA", "MIN_MAX_MEAN")

# Process: Join Field
arcpy.JoinField_management(out_countries, "Country", s_countries, "Country", "Min;Max;Mean")







